Telescope.strings.ru = {
  "forms.submit": "Отправить",
  "forms.cancel": "Отмена",

  "posts.new_post": "Новый пост",
  "posts.edit": "Редактировать",
  "posts.edit_success": "Пост “{title}” отредактирован.",
  "posts.delete": "Удалить",
  "posts.delete_confirm": "Удалить пост “{title}”?",
  "posts.delete_success": "Пост “{title}” удален.",
  "posts.title": "Название",
  "posts.url": "URL",
  "posts.body": "Текст",
  "posts.categories": "Категории",
  "posts.thumbnailUrl": "URL Миниатюры",
  "posts.status": "Статус",
  "posts.sticky": "Закрепить",
  "posts.load_more": "Показать ещё",
  "posts.search": "Поиск",
  "posts.view": "Сортировать",
  "posts.top": "Популярные",
  "posts.new": "Новые",
  "posts.best": "Лучшие",
  "posts.pending": "Ожидающие",
  "posts.rejected": "Отклоненные",
  "posts.scheduled": "Запланированные",
  "posts.daily": "По дням",
  "posts.clear_thumbnail": "Убрать миниатюру",
  "posts.enter_thumbnail_url": "Введите URL",
  "posts.created_message": "Пост создан.",
  "posts.rate_limit_error": "Пожалуйста, подождите {details} секунд перед повторной публикацией.",

  "comments.comments": "Комментарии",
  "comments.count": "{count, plural, =0 {Нет комментариев} one {# комментарий} other {# комментариев}}",
  "comments.new": "Новый комментарий",
  "comments.no_comments": "Нет комментариев",
  "comments.reply": "Ответить",
  "comments.edit": "Редактировать",
  "comments.delete": "Удалить",
  "comments.delete_confirm": "Удалить комментарий “{body}”?",
  "comments.delete_success": "Комментарий “{body}” удален.",
  "comments.please_log_in": "Пожалуйста авторизуйтесь, чтобы комментировать",
  "comments.parentCommentId": "ID родительского комментария",
  "comments.topLevelCommentId": "ID комментария верхнего уровеня",
  "comments.body": "Текст",
  "comments.rate_limit_error": "Пожалуйста, подождите {details} секунд перед повторным комментированием.",

  "users.profile": "Профиль",
  "users.complete_profile": "Заполните свой профиль",
  "users.edit_account": "Редактировать профиль",
  "users.log_in": "Войти",
  "users.log_out": "Выйти",
  "users.telescope.bio": "Обо мне",
  "users.telescope.displayName": "Отображаемое Имя",
  "users.telescope.email": "Email",
  "users.telescope.twitterUsername": "Twitter",
  "users.telescope.website": "Website",
  "users.notifications": "Уведомления",
  "users.telescope.notifications_users": "Уведомление о пользователях",
  "users.telescope.notifications_posts": "Уведомление о новых постах",
  "users.telescope.newsletter_subscribeToNewsletter": "Подписаться на рассылку",
  "users.admin": "Администратор",
  "users.isAdmin": "Админ",
  "users.posts": "Пост",
  "users.please_log_in": "Пожалуйста, авторизуйтесь",
  "users.cannot_post": "К сожалению, у вас нет прав на публикацию поста",

  "categories": "Категории",
  "categories.all": "Все категории",
  "categories.edit": "Редактировать категорию",
  "categories.new": "Новая категория",
  "categories.delete": "Удалить категорию",
  "categories.name": "Имя",
  "categories.description": "Описание",
  "categories.order": "Порядок",
  "categories.slug": "Псевдоним",
  "categories.image": "Картинка",
  "categories.parentId": "Родительский ID",

  "settings": "Настройки",
  "settings.json_message": "Note: settings already provided in your <code>settings.json</code> file will be disabled.",
  "settings.edit": "Редактировать настройки",
  "settings.edited": "Settings edited (please reload).",
  "settings.title": "Title",
  "settings.siteUrl": "Site URL",
  "settings.tagline": "Tagline",
  "settings.description": "Description",
  "settings.siteImage": "Site Image",
  "settings.defaultEmail": "Default Email",
  "settings.mailUrl": "Mail URL",
  "settings.scoreUpdate": "Score Update",
  "settings.postInterval": "Post Interval",
  "settings.RSSLinksPointTo": "RSS Links Point To",
  "settings.commentInterval": "Comment Interval",
  "settings.maxPostsPerDay": "Max Posts Per Day",
  "settings.startInvitesCount": "Start Invites Count",
  "settings.postsPerPage": "Posts Per Page",
  "settings.logoUrl": "Logo URL",
  "settings.logoHeight": "Logo Height",
  "settings.logoWidth": "Logo Width",
  "settings.faviconUrl": "Favicon URL",
  "settings.twitterAccount": "Twitter Account",
  "settings.facebookPage": "Facebook Page",
  "settings.googleAnalyticsId": "Google Analytics ID",
  "settings.locale": "Locale",
  "settings.requireViewInvite": "Require View Invite",
  "settings.requirePostInvite": "Require Post Invite",
  "settings.requirePostsApproval": "Require Posts Approval",
  "settings.scoreUpdateInterval": "Score Update Interval",

  "app.loading": "Загрузка…",
  "app.404": "К сожалению, мы не смогли найти то, что вы искали.",
  "app.powered_by": "Работает на Telescope",
  "app.or": "Или",

  "newsletter": "Рассылка",
  "newsletter.subscribe": "Подписаться",
  "newsletter.unsubscribe": "Отписаться",
  "newsletter.subscribe_prompt": "Подписаться на рассылку новостей",
  "newsletter.email": "Ваш email",
  "newsletter.success_message": "Спасибо за то, что подписались!",

  "admin": "Администратор",
  "notifications": "Уведомления",
}
